# Generated by Django 3.2.15 on 2023-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_watchlater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='watch_id',
        ),
        migrations.AddField(
            model_name='watchlater',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
