# Generated by Django 3.2.15 on 2023-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20230420_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='USER', max_length=1000)),
                ('music', models.CharField(max_length=1000000)),
            ],
        ),
    ]
