# Generated by Django 3.2.15 on 2023-04-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.FileField(upload_to='songs/covers'),
        ),
    ]
